AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  UnicornLoyalty:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: UnicornLoyalty/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies: AmazonDynamoDBFullAccess
      Environment: 
        Variables: 
          TABLE_NAME: 
            Ref: UsersTable
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: itemId
        Type: String
  OrdersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "orderId"
          AttributeType: "S"
        -
          AttributeName: "itemId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "orderId"
          KeyType: "HASH"
        -
          AttributeName: "itemId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
